apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-grpc-server
  labels:
    app: hello-grpc-server
spec:
  selector:
    matchLabels:
      app: hello-grpc-server
  template:
    metadata:
      labels:
        app: hello-grpc-server
    spec:
      containers:
      - name: hello-grpc-server
        image: registry.cn-beijing.aliyuncs.com/husterdjx/husterdjx:grpc-server
        imagePullPolicy: Always
        ports:
        - containerPort: 50053
          name: http
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hello-grpc-server-service
spec:
  selector:
    app: hello-grpc-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50053