apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-grpc-client
  labels:
    app: hello-grpc-client
spec:
  selector:
    matchLabels:
      app: hello-grpc-client
  template:
    metadata:
      labels:
        app: hello-grpc-client
    spec:
      containers:
      - name: hello-grpc-client
        image: registry.cn-beijing.aliyuncs.com/husterdjx/husterdjx:grpc-client
        imagePullPolicy: Always
        ports:
        - containerPort: 50060
          name: http
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 50Mi