apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-grpc
  labels:
    app: hello-grpc
spec:
  selector:
    matchLabels:
      app: hello-grpc
  template:
    metadata:
      labels:
        app: hello-grpc
    spec:
      containers:
      - name: husterdjx
        image: registry.cn-beijing.aliyuncs.com/husterdjx/husterdjx:{{.build_tag}}
        ports:
        - containerPort: 50052
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 100m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hello-grpc
  labels:
    app: hello-grpc
spec:
  selector:
    app: hello-grpc
  type: ClusterIP
  ports:
    - name: web
      port: 50052
      targetPort: http