apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-http
  labels:
    app: hello-http
spec:
  selector:
    matchLabels:
      app: hello-http
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-http
    spec:
      containers:
      - name: hello-http
        image: registry.cn-beijing.aliyuncs.com/husterdjx/husterdjx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50052
          name: http
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hello-http
spec:
  selector:
    app: hello-http
  ports:
    - port: 6666
      targetPort: 50052
      name: hello-http