name: docker-ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build Backend and push
        id: docker_backend_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.cn-beijing.aliyuncs.com/husterdjx/husterdjx:latest
      - name: Backend Image digest
        run: echo ${{ steps.docker_backend_build.outputs.digest }}