name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build the Docker image
      run: | 
        docker version
        # 登录阿里云镜像仓库
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-beijing.aliyuncs.com
        # 使用Dockerfile构建镜像
        docker build . -f code/http/Dockerfile --tag registry.cn-beijing.aliyuncs.com/husterdjx/husterdjx:latest
        # 推送镜像到镜像仓库
        docker push registry.cn-beijing.aliyuncs.com/husterdjx/husterdjx:latest
      working-directory: ./code/http